---
- name: playbook
  hosts: all
  become: true
  tasks:
    - name: httpd installation
      yum:
        name: httpd
        state: present

    - name: stop firewalld
      service:
        name: firewalld
        state: stopped
        enabled: false

    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: true
    
    - name: creating index.html
      get_url: url=https://www.naver.com dest=/var/www.html/index.html 
